name: weather
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  geolocator: ^10.0.0
  dio: ^5.3.2
  translator: ^0.1.7
  country_codes: ^2.2.0
  crypto: ^3.0.3
  hive: ^2.2.3
  path_provider: ^2.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/big_weather/
    - assets/images/small_weather/
    - assets/images/icons/
    - assets/fonts/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300


