// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj9jwrUCL-cie6LuwdlpOCX7JYSEXtdCg',
    appId: '1:872539365370:web:6e6e6a9ed038a37e1cce43',
    messagingSenderId: '872539365370',
    projectId: 'weather-1ac5b',
    authDomain: 'weather-1ac5b.firebaseapp.com',
    storageBucket: 'weather-1ac5b.appspot.com',
    measurementId: 'G-15WPDBCG9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrATrK3PTwO-VL8UyUI16H_LkkD6W28Do',
    appId: '1:872539365370:android:0ebb06aa14fb59261cce43',
    messagingSenderId: '872539365370',
    projectId: 'weather-1ac5b',
    storageBucket: 'weather-1ac5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiWtJsDaLRmH4xLmLgDuFuf7368AFhZj0',
    appId: '1:872539365370:ios:f52e788bf69d1db61cce43',
    messagingSenderId: '872539365370',
    projectId: 'weather-1ac5b',
    storageBucket: 'weather-1ac5b.appspot.com',
    iosClientId: '872539365370-6ticu84jg5mt2t93ek3hi8a9oaehmbmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiWtJsDaLRmH4xLmLgDuFuf7368AFhZj0',
    appId: '1:872539365370:ios:94b418edf3606bc61cce43',
    messagingSenderId: '872539365370',
    projectId: 'weather-1ac5b',
    storageBucket: 'weather-1ac5b.appspot.com',
    iosClientId: '872539365370-o3ldbtsasjlhmaksnmpen7k8a27oelmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.weather.RunnerTests',
  );
}
